#! /bin/sh

#picom -f &
lxpolkit &
feh --bg-scale ~/Pictures/Gi_Hun.png &
$HOME/.config/polybar/launch.sh
#discord &
#discord-ptb &
#steam

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a \* node="@/2" split_dir="south"
bspc rule -a discord desktop='^2'
bspc rule -a discord-ptb desktop='^2'
bspc rule -a steam desktop='^3'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
